import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

/** Locales that have a template folder under `prompts/`. */
export const TEMPLATE_LOCALES = ['fr', 'en'] as const;

export type TemplateFiles = Record<string, Record<string, string>>;

/** Absolute path of the repository's `prompts/` folder. */
export const PROMPTS_DIR = join(import.meta.dirname, '..', '..', '..', 'prompts');

/** Normalizes a template file: LF line endings, no trailing blank lines or spaces at the end. */
export function normalizeTemplate(text: string): string {
  return text.replace(/\r\n?/g, '\n').replace(/\s+$/, '');
}

/** Reads every `prompts/<locale>/*.md` file, keyed by locale then by name (without `.md`). */
export function readTemplateFiles(dir: string = PROMPTS_DIR): TemplateFiles {
  const out: TemplateFiles = {};
  for (const locale of TEMPLATE_LOCALES) {
    const files: Record<string, string> = {};
    const names = readdirSync(join(dir, locale))
      .filter((f) => f.endsWith('.md'))
      .sort();
    for (const file of names) {
      files[file.slice(0, -3)] = normalizeTemplate(readFileSync(join(dir, locale, file), 'utf8'));
    }
    out[locale] = files;
  }
  return out;
}

/** Source of `src/templates.generated.ts` for the given template files. */
export function renderTemplatesModule(files: TemplateFiles): string {
  const names = Object.keys(files.fr ?? {});
  const lines = [
    '// Generated by `pnpm --filter @mnemo/prompts templates` from prompts/{fr,en}/*.md.',
    '// Do not edit by hand: edit the .md files and run the script again (a test checks it).',
    "import type { Locale } from '@mnemo/core';",
    '',
    `export const TEMPLATE_NAMES = ${JSON.stringify(names)} as const;`,
    'export type TemplateName = (typeof TEMPLATE_NAMES)[number];',
    '',
    'export const TEMPLATES: Readonly<Record<Locale, Readonly<Record<TemplateName, string>>>> = {',
  ];
  for (const locale of TEMPLATE_LOCALES) {
    lines.push(`  ${locale}: {`);
    for (const name of names) {
      lines.push(`    ${JSON.stringify(name)}: ${JSON.stringify(files[locale]?.[name] ?? '')},`);
    }
    lines.push('  },');
  }
  lines.push('};', '');
  return lines.join('\n');
}
